version: '3'
services:

  redis:
    image: redis:6.2.6-alpine
    container_name: redis-streams-zio-redis
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6377:6377

  # https://docs.redislabs.com/latest/ri/installing/install-docker/
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-streams-zio-redis-insight
    restart: unless-stopped
    volumes:
      - ./docker-volumes/redisinsight:/db
    ports:
      - 8002:8001
